name: Publish

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20
      - run: npm install
      - run: xvfb-run -a npm test
      - name: Publish
        if: success()
        run: npm run publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
